# This file can be used to customize the files managed by PDK.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/README.md
# for more information.
#
# See https://github.com/puppetlabs/pdk-templates/blob/main/config_defaults.yml
# for the default values.
---
.rubocop.yml:
  include_todos: true
spec/spec_helper.rb:
  mock_with: ":rspec"
  coverage_report: true
.gitignore:
  paths:
    - "/spec/fixtures/litmus_inventory*.yaml"
    - "/.bolt/"
    - "/.litmus/"
.pdkignore:
  paths:
    - "/spec/fixtures/litmus_inventory*.yaml"
    - "/.bolt/"
    - "/.litmus/"
